# revision 29803
# category Package
# catalog-ctan /info/examples/Presentations_en
# catalog-date 2012-08-22 17:34:41 +0200
# catalog-license lppl
# catalog-version undef
Name:		texlive-presentations-en
Version:	20120822
Release:	8
Summary:	Examples from the book Presentations with LaTeX
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/info/examples/Presentations_en
License:	LPPL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/presentations-en.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/presentations-en.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg

%description
This bundle contains all the examples, as source, eps and pdf,
of the author's book "Presentations with LaTeX", from the
Dante-Edition series, Published by Lehmanns Media.

#-----------------------------------------------------------------------
%files
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-01-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-01-2.ltx2ps
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-01-3.ltx2
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-01-4.ltx2
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-01-5.ltx2ps
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-01-6.ltx2
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-02-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-03-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-03-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/01-03-5.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-01-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-01-2.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-01-3.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-02-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-03-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-03-2.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-03-3.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-03-4.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-04-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-04-2.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-04-3.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-04-4.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-04-5.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-04-6.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-04-7.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-04-8.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-05-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-06-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-06-2.ltxps
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-07-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-09-1.ltxps
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-10-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-10-2.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-10-3.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-10-4.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-10-5.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-10-6.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-11-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-12-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-12-2.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-13-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-13-2.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-13-3.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-10.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-11.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-12.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-13.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-14.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-15.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-16.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-17.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-18.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-19.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-2.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-3.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-4.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-5.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-6.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-7.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-8.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/02-14-9.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/03-01-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/03-02-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/03-03-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/03-03-2.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/03-04-1.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-01-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-01-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-01-3.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-01-4.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-03-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-03-2.ltx2
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-04-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-05-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-10.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-11.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-3.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-4.ltxbps
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-5.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-6.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-7.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-8.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-06-9.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-07-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-08-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-09-1.ltxbps
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-11-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-11-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-11-3.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-12-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-12-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-13-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-13-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-14-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-15-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-15-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-16-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-16-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-16-3.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-17-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-18-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-18-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-19-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-19-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-20-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-20-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-20-3.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-20-4.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-20-5.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-22-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-22-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-22-3.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-22-4.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-23-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-23-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-23-3.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-24-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-24-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-25-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-25-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-26-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-26-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-26-3.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-26-4.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-10.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-11.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-12.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-13.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-14.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-15.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-16.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-17.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-18.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-19.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-20.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-21.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-22.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-23.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-24.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-25.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-26.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-27.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-28.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-29.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-3.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-30.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-31.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-32.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-33.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-34.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-35.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-36.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-37.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-38.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-39.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-4.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-40.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-41.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-42.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-43.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-44.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-45.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-46.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-47.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-48.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-49.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-5.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-50.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-51.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-52.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-53.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-54.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-55.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-56.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-57.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-58.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-59.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-6.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-60.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-61.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-62.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-63.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-64.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-65.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-7.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-8.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/04-27-9.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/05-00-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/05-01-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/05-02-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/05-03-1.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/05-03-2.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-01-2.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-01-3.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-01-4.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-01-5.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-01-6.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-01-7.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-02-1.ltxps
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-04-3.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/06-05-1.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/07-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/07-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/presentations-en/07-03-3.ltxpd
%doc %{_texmfdistdir}/doc/latex/presentations-en/07-03-4.ltxb
%doc %{_texmfdistdir}/doc/latex/presentations-en/07-05-1.ltxbps
%doc %{_texmfdistdir}/doc/latex/presentations-en/07-05-2.ltxbps
%doc %{_texmfdistdir}/doc/latex/presentations-en/DEexa.sty
%doc %{_texmfdistdir}/doc/latex/presentations-en/DEoptions.sty
%doc %{_texmfdistdir}/doc/latex/presentations-en/PPRtime.sty
%doc %{_texmfdistdir}/doc/latex/presentations-en/README
%doc %{_texmfdistdir}/doc/latex/presentations-en/Textdemo.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/beamer-demo-en.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/beamer-demo.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/beamer-demo2.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/beispiel.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/bspcalweekly.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/bspdvdcoll.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/bspfont.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/bsppstricks.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/buch-E.bib
%doc %{_texmfdistdir}/doc/latex/presentations-en/buch.bib
%doc %{_texmfdistdir}/doc/latex/presentations-en/exa-fontconfig.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/exaarticle.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exaarticle2.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exaartplain.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exabeamer.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exabook.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exabook2.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exadante.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exafoils.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exafubeamer.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exafupd.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/examargin.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/examemoir.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/examinimal-mathsymbols.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/examinimal.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exapd.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exaprosper.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exareport.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exaseminar.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exaslidenotes.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exasymbol.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/exaxetex.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/fontDemo-E.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/fontDemo.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/TU.jpg
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/TeX.pdf
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/beamer0.pdf
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/beamer1.pdf
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/beamer2.pdf
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/beamernavbar.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/beamernavsymbols.pdf
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/beamernavsymbols.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/grating.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/ligaturen.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/multimedia.jpg
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/multimedia.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/transition1.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/beamer/zedat.pdf
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/clemson.gif
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/clemson.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/logo-clemson.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/logofbbw.eps
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/moviePD.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/pawmkorange.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/pawmkpurple.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/pawtraceorange.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/pawtracep.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/wieesgeht.eps
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pd/zedat2.eps
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pdfscreen/Tore3d.pdf
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pdfscreen/mp.pdf
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pdfscreen/mpgraph.mps
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pdfscreen/pst.pdf
%doc %{_texmfdistdir}/doc/latex/presentations-en/images/pdfscreen/tex.png
%doc %{_texmfdistdir}/doc/latex/presentations-en/obox.sty
%doc %{_texmfdistdir}/doc/latex/presentations-en/pd-demo-default.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/pd-demo.tex
%doc %{_texmfdistdir}/doc/latex/presentations-en/powerdot-clemson.sty
%doc %{_texmfdistdir}/doc/latex/presentations-en/prosper.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/runAll
%doc %{_texmfdistdir}/doc/latex/presentations-en/screxa.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/screxabook.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/screxareport.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/slidenotes.cfg
%doc %{_texmfdistdir}/doc/latex/presentations-en/slidenotes.cls
%doc %{_texmfdistdir}/doc/latex/presentations-en/textdemo.sty

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar doc %{buildroot}%{_texmfdistdir}
